# Stage 1: Build dependencies
FROM python:3.14-slim AS builder

WORKDIR /app

# Instalar dependências de compilação
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# Criar pacotes wheel (pré-compilados) para não precisar do gcc no runtime
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.txt

# Stage 2: Runtime Image
FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instalar Node.js, npm, e as bibliotecas mínimas do postgres
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    postgresql-client \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/* \
    && npm cache clean --force

# Copiar os bibliotecas wheel pré-compiladas
COPY --from=builder /app/wheels /wheels
COPY --from=builder /app/requirements.txt .

# Instalar a partir dos pacotes wheel sem cache de pip
RUN pip install --no-cache /wheels/* \
    && rm -rf /wheels \
    && rm requirements.txt

COPY . .

RUN python manage.py collectstatic --noinput

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
