FROM postgres:16

LABEL maintainer="freecash"
LABEL description="PostgreSQL for FreeCash project"

ENV TZ=America/Sao_Paulo

RUN ln -snf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
    && echo "America/Sao_Paulo" > /etc/timezone
