FROM postgres:16-alpine

LABEL maintainer="freecash"
LABEL description="PostgreSQL for FreeCash project optimized"

ENV TZ=America/Sao_Paulo

# Instalar o tzdata e configurar timezone para a imagem Alpine
RUN apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && apk del tzdata
