# Generated by Django 6.0.6 on 2026-08-29 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('cnpj', models.CharField(blank=True, help_text='Somente números (14 dígitos) para atualização via CVM', max_length=14, null=True, verbose_name='CNPJ do Fundo')),
                ('moeda', models.CharField(default='BRL', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('meta_porcentagem', models.DecimalField(decimal_places=2, default=0, help_text='Porcentagem alvo deste ativo na carteira', max_digits=5, verbose_name='Meta (%)')),
                ('quantidade', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('preco_medio', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='ClasseAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=60)),
                ('ativa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_ativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classe de Ativo',
                'verbose_name_plural': 'Classes de Ativos',
                'ordering': ['nome'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=60)),
                ('ativa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_ativos', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='investimento.classeativo')),
            ],
            options={
                'verbose_name': 'Categoria de Ativo',
                'verbose_name_plural': 'Categorias de Ativos',
                'ordering': ['nome'],
                'unique_together': {('usuario', 'classe', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='DetalheRendaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('emissor', models.CharField(blank=True, max_length=100, verbose_name='Emissor (Banco/Empresa)')),
                ('indexador', models.CharField(blank=True, choices=[('CDI', 'CDI'), ('IPCA', 'IPCA'), ('SELIC', 'SELIC'), ('PRE', 'Pré-fixado'), ('IGPM', 'IGP-M'), ('OUTROS', 'Outros')], max_length=10, verbose_name='Indexador')),
                ('taxa', models.DecimalField(decimal_places=4, default=0, help_text='Ex: 100 para 100% do CDI ou 6.5 para IPCA+6.5%', max_digits=9, verbose_name='Taxa / Porcentagem')),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhe_renda_fixa', to='investimento.ativo')),
            ],
            options={
                'verbose_name': 'Detalhe de Renda Fixa',
                'verbose_name_plural': 'Detalhes de Renda Fixa',
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=60)),
                ('ativa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='investimento.categoriaativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias_ativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subcategoria de Ativo',
                'verbose_name_plural': 'Subcategorias de Ativos',
                'ordering': ['categoria__classe__nome', 'categoria__nome', 'nome'],
                'unique_together': {('usuario', 'categoria', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='ativo',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='investimento.subcategoriaativo'),
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda'), ('D', 'Provento (Dividendo/JCP)')], max_length=1)),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=8, max_digits=19)),
                ('preco_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('taxas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='investimento.ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_investimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='CarteiraHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('patrimonio', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total_compras', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total_dividendos', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('rentabilidade', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('rentabilidade_percentual', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteira_historico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-criada_em'],
                'unique_together': {('usuario', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=19)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='investimento.ativo')),
            ],
            options={
                'ordering': ['-data', '-criada_em'],
                'unique_together': {('ativo', 'data')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ativo',
            unique_together={('usuario', 'ticker')},
        ),
    ]
