# Generated by Django 6.0.6 on 2026-09-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='historico_verificado_em',
            field=models.DateField(blank=True, help_text='Última vez que a atualização em lote conferiu a cobertura da série de cotações deste ativo no Yahoo Finance.', null=True, verbose_name='Histórico verificado em'),
        ),
    ]
