# Generated by Django 6.0.6 on 2026-08-29 00:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('bandeira', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('ELO', 'Elo'), ('AMEX', 'American Express'), ('HIPERCARD', 'Hipercard'), ('DINERS', 'Diners Club'), ('OUTRO', 'Outro')], default='VISA', max_length=20)),
                ('ultimos_digitos', models.CharField(blank=True, max_length=4)),
                ('limite', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dia_fechamento', models.IntegerField(default=1)),
                ('dia_vencimento', models.IntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa'), ('I', 'Investimento')], max_length=1)),
                ('is_default', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ConfigUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('moeda_padrao', models.CharField(default='BRL', max_length=10)),
                ('ultimo_export_em', models.DateTimeField(blank=True, null=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('email_verificado_em', models.DateTimeField(blank=True, null=True)),
                ('email_pendente', models.EmailField(blank=True, default='', max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtratoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('banco', models.CharField(choices=[('nubank', 'Nubank'), ('inter', 'Banco Inter'), ('itau', 'Itaú'), ('bradesco', 'Bradesco'), ('bb', 'Banco do Brasil'), ('caixa', 'Caixa Econômica'), ('santander', 'Santander'), ('generico', 'Genérico')], default='generico', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processado', 'Processado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('linhas_encontradas', models.IntegerField(default=0)),
                ('linhas_importadas', models.IntegerField(default=0)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('data_vencimento', models.DateField(blank=True, help_text='Data de vencimento da fatura associada a este extrato', null=True)),
                ('cartao', models.ForeignKey(blank=True, help_text='Cartão de crédito associado a este extrato (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extratos', to='core.cartaocredito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratos_importados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extrato Importado',
                'verbose_name_plural': 'Extratos Importados',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], db_index=True, default='R', max_length=1)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequencia', models.CharField(choices=[('mensal', 'Mensal'), ('quinzenal', 'Quinzenal'), ('semanal', 'Semanal'), ('anual', 'Anual')], default='mensal', max_length=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_recorrentes', to='core.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_recorrentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento Recorrente',
                'verbose_name_plural': 'Lançamentos Recorrentes',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa'), ('I', 'Investimento')], max_length=1)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_prevista', models.DateField(db_index=True)),
                ('transacao_realizada', models.BooleanField(db_index=True, default=False)),
                ('data_realizacao', models.DateField(blank=True, db_index=True, null=True)),
                ('data_compra', models.DateField(blank=True, db_index=True, null=True)),
                ('eh_fatura_cartao', models.BooleanField(db_index=True, default=False, help_text='Marca se este registro é uma fatura de cartão (não uma despesa individual)')),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='core.cartaocredito')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas', to='core.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to=settings.AUTH_USER_MODEL)),
                ('recorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='core.lancamentorecorrente')),
            ],
            options={
                'ordering': ['-data_prevista', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LinhaExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=500)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], max_length=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('importado', 'Importado'), ('ignorado', 'Ignorado')], default='pendente', max_length=20)),
                ('conta_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_extrato', to='core.conta')),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='core.extratoimportado')),
            ],
            options={
                'verbose_name': 'Linha de Extrato',
                'verbose_name_plural': 'Linhas de Extrato',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LogAcaoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('ator_username', models.CharField(max_length=150)),
                ('alvo_username', models.CharField(max_length=150)),
                ('acao', models.CharField(choices=[('suspender', 'Suspender conta'), ('reativar', 'Reativar conta')], max_length=20)),
                ('detalhe', models.TextField(blank=True, default='')),
                ('alvo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_admin_recebidas', to=settings.AUTH_USER_MODEL)),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_admin_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de ação administrativa',
                'verbose_name_plural': 'Logs de ações administrativas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('patrimonio_renda', 'Patrimônio para viver de renda'), ('aporte_mensal', 'Meta mensal investimento'), ('reserva_emergencia', 'Reserva de emergência'), ('gasto_essencial', 'Limite de gastos essenciais'), ('personalizada', 'Personalizada')], default='personalizada', max_length=30)),
                ('natureza', models.CharField(choices=[('acumulo', 'Acúmulo'), ('teto', 'Teto mensal')], default='acumulo', max_length=10)),
                ('base_calculo', models.CharField(choices=[('renda', 'Renda mensal'), ('custo_vida', 'Custo de vida mensal'), ('manual', 'Valor manual')], default='manual', max_length=15)),
                ('multiplicador', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('valor_alvo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('origem_acumulado', models.CharField(choices=[('manual', 'Informado manualmente'), ('carteira', 'Valor de mercado da carteira'), ('aportes_mes', 'Aportes do mês na carteira')], default='manual', max_length=15)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=99)),
                ('observacao', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AporteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='core.metafinanceira')),
            ],
            options={
                'verbose_name': 'Aporte de Meta',
                'verbose_name_plural': 'Aportes de Metas',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanoMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('custo_vida_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usar_valores_automaticos', models.BooleanField(default=True)),
                ('meses_referencia', models.PositiveSmallIntegerField(default=3)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Metas',
                'verbose_name_plural': 'Planos de Metas',
            },
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['usuario', 'tipo', 'data_prevista'], name='core_conta_usuario_7b1848_idx'),
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['usuario', 'transacao_realizada', 'data_realizacao'], name='core_conta_usuario_9d18e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metafinanceira',
            unique_together={('usuario', 'nome')},
        ),
    ]
