# Generated by Django 6.0.6 on 2026-10-07 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_email_unico_case_insensitive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fora_dos_relatorios', models.BooleanField(default=True, help_text='Se True, os lançamentos do evento entram no saldo, mas não nas agregações de período.')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-inicio', 'nome'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='conta',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='core.evento'),
        ),
    ]
